### ISSUE TITLE
Add support for drush en (enable) and drush dis (disable)

### ISSUE THREAD

**Issue by serundeputy** [backdrop-contrib/drush#7]
Allow Backdrop CMS users to enable and/or disable modules from the command line.

 * `drush en {module_name}`
 * `drush dis {module_name}`

----

* ~~PR https://github.com/backdrop-contrib/drush/pull/40~~
* ~~PR: https://github.com/backdrop-contrib/drush/pull/51~~
* ~~PR: https://github.com/backdrop-contrib/drush/issues/52~~
* ~~PR: #80~~
* PR: https://github.com/backdrop-contrib/drush/pull/98

**Comment by serundeputy** [comment]
This PR: https://github.com/backdrop-contrib/drush/pull/40 is calling the Backdrop API `module_enable` and it is setting the status of the module to 1 in the DB, but is not running the install functions.  So, for example the config forms of the modules are not available in the backdrop UI.

patch: https://github.com/backdrop-contrib/drush/pull/40.patch

For example run these commands (with the patch applied):
-  `drush dl on_the_web`
- `drush en on_the_web`
- Visit `admin/config/services/on_the_web` it brings you to `admin/config/services`

But if you install through Backdrop UI the config form is there?

**Comment by serundeputy** [comment]
PR #51 added `en` support I'll file a separate issue for `dis` to keep concerns separate.

**Comment by serundeputy** [comment]
Looks like we are having some form of the namespacing issue again that conflicts with D7 commands (@quicksketch comment: https://github.com/backdrop-contrib/drush/issues/14#issuecomment-201516214)

I've namespaced the `backdrop-pm-enable` command callback as `backdrop_command_pm_enable`, but still in the context of a D7 site this command is being called:

```
geoff@gspmbp vanilla $ drush en webform -v
Undefined index: description command.inc:1245                                                                                                                           [notice]
Undefined index: description command.inc:1245                                                                                                                           [notice]
Undefined index: description command.inc:1245                                                                                                                           [notice]
Executing: mysql --defaults-extra-file=/private/tmp/drush_FK49J3 --database=vanilla --host=localhost --silent  < /private/tmp/drush_dNWjxA
Executing: mysql --defaults-extra-file=/private/tmp/drush_xO2wpg --database=vanilla --host=localhost --silent  < /private/tmp/drush_zQf9Yy
Undefined index: description command.inc:1245                                                                                                                           [notice]
Undefined index: description command.inc:1245                                                                                                                           [notice]
Undefined index: description command.inc:1245                                                                                                                           [notice]
Use of undefined constant BACKDROP_ROOT - assumed 'BACKDROP_ROOT' backdrop_pm_enable.drush.inc:105                                                                      [notice]
Use of undefined constant BACKDROP_ROOT - assumed 'BACKDROP_ROOT' backdrop_pm_enable.drush.inc:106                                                                      [notice]

        Error webform does not exist in your Backdrop installation.
        Try downloading webform first with the command: drush dl webform

Command dispatch complete
```

I noticed that the `drush` proper was not specifying a callback `commands/pm/pm.drush.inc`. I tried to specify `drush_pm_enable` as the callback, but it still calls the backdrop implementation.

@quicksketch can you see a connection?

~Geoff

**Comment by jenlampton** [comment]
I'm also seeing this.  On a Drupal 7 site `drush status` knows that it's Drupal 7 (`Drupal version                  :  7.50`) but `drush en` now thinks the site is Backdrop and throws an error `Error elements does not exist in your Backdrop installation.
    Try downloading elements first with the command: drush dl elements`

**Comment by serundeputy** [comment]
This PR: https://github.com/backdrop-contrib/drush/pull/80

Allows you to enable and disable modules via the commands:

  * `drush en {module_name(s)}`
  * `drush dis {module_name(s)}`

In my testing it did not break Drupal 7 `en` and `dis` drush commands.

@jenlampton or anybody up for testing?

**Comment by jenlampton** [comment]
yes!

**Comment by jenlampton** [comment]
Well, I checked out the `remotes/serundeputy/7/pm-enable` branch of the drush commands, ran a `drush cc drush` and then tried a `drush en forward -y` on one of my existing Drupal 7 sites. I still get this error:
```
Error forward does not exist in your Backdrop installation.
Try downloading forward first with the command: drush dl forward
```

Did I miss a step?

**Comment by serundeputy** [comment]
@jenlampton try `git pull serundeputy 7/pm-enable`?

see if that brings down the new code for you.

**Comment by serundeputy** [comment]
I'm on this commit:

```
52a0752 - (HEAD -> 7/pm-enable, origin/7/pm-enable) Issue #7: Add support for pm-enable and pm-disable modules. (32 hours ago) <Geoff St. Pierre>
```

**Comment by jenlampton** [comment]
I pulled, did get some new files!  Also on `52a0752b65365c` now.  Tried `drush cc drush`, then `drush en forward -y` and still got...

```
Error forward does not exist in your Backdrop installation.
Try downloading forward first with the command: drush dl forward
```

**Comment by jenlampton** [comment]
`drush en forward -y -vvv` gives:

```
Undefined index: description command.inc:1245                                                                                           [notice]
Undefined index: description command.inc:1245                                                                                           [notice]
Undefined index: description command.inc:1245                                                                                           [notice]
Undefined index: description command.inc:1245                                                                                           [notice]
Executing: mysql --defaults-extra-file=/private/tmp/drush_jTdFK9 --database=kvmr --host=localhost --silent  < /private/tmp/drush_6gSRwh
Executing: mysql --defaults-extra-file=/private/tmp/drush_TZphCR --database=kvmr --host=localhost --silent  < /private/tmp/drush_4E1Q3W
Undefined index: description command.inc:1245                                                                                           [notice]
Undefined index: description command.inc:1245                                                                                           [notice]
Undefined index: description command.inc:1245                                                                                           [notice]
Undefined index: description command.inc:1245                                                                                           [notice]
Use of undefined constant BACKDROP_ROOT - assumed 'BACKDROP_ROOT' backdrop_pm_enable.drush.inc:105                                      [notice]
Use of undefined constant BACKDROP_ROOT - assumed 'BACKDROP_ROOT' backdrop_pm_enable.drush.inc:106                                      [notice]

	Error forward does not exist in your Backdrop installation.
	Try downloading forward first with the command: drush dl forward

Command dispatch complete  
```

**Comment by serundeputy** [comment]
shucks :(

@jenlampton what is your drush version?

me:

```
geoff@gspmbp backdrop (7/pm-enable) $ drush --version
 Drush Version   :  8.2-dev
```

**Comment by jenlampton** [comment]
me too: `Drush Version   :  8.2-dev` commit `58d4c1328f188fd1eb1bb542d21444fc6314f8c9`

**Comment by jenlampton** [comment]
If I pull the latest drush 8.x branch, a `drush cc drush` throws:
```
Fatal error: Class 'Consolidation\AnnotatedCommand\AnnotationData' not found in drush-8/includes/command.inc on line 1266
Drush command terminated abnormally due to an unrecoverable error.   [error]
Error: Class 'Consolidation\AnnotatedCommand\AnnotationData' not
found in drush-8/includes/command.inc, line 1266
```

**Comment by serundeputy** [comment]
@jenlampton do you have backups of old versions of the `backdrop drush` extension and if so are they in either your `~/.drush` or `~/drush` folder?

If so it could be picking up on those and loading them after the one we intend.  Shot in the dark, but please check if you have any backup files that contain the old `drush en` command.

~Geoff

**Comment by jenlampton** [comment]
I do not have a ` ~/.drush` or `~/drush` folder.  My drushes are all organized by version (and alias):
```
~/drush-5
~/drush-6
~/drush-7
~/drush-8
```

The only copy of backdrop drush I have is in the `~/drush-8/commands` directory, and it is a git checkout with remotes for contrib as well as your fork so that I can pull and test branches (PRs) as needed.

My current process is to use drush 7 on drupal 7 (since drush 8 is broken on Drupal 7 with backdrop commands present). I have them all set up to be used separately so I can switch back and forth.

**Comment by serundeputy** [comment]
@jenlampton I see. Thanks for the detailed response.

I'll try to see if I move my backdrop drush extension to `~/drush-{#}` if I can replicate the issue.

thanks.  More to come once I test that scenario.

**Comment by jenlampton** [comment]
I don't think that's likely the problem, but I'm also out of other ideas as to why we are getting different results!

**Comment by serundeputy** [comment]
@jenlampton you're right; works for me in `~/drush/commands` and in `~/.drush/extensions` ... hrm.

Not sure where to go from here: @quicksketch @wesruv can one or both of you apply this patch and see if you get same results as @jenlampton or me or something entirely different?

**Comment by wesruv** [comment]
I gave it a college try, but I'm having issues getting drush to realize it has an enable command. Definitely something on my side, I have a custom docker setup that I'm not particularly good at modifying... sorry 😞

**Comment by jenlampton** [comment]
I've also noticed that `drush en` seems to only work for contrib, not for core or custom modules.

**Comment by serundeputy** [comment]
@jenlampton I believe I've fixed:

*  the conflict with `en/dis` breaking drupal 7 sites
* drush `en/dis` should work with core, contrib, and custom modules now

up for another round of testing?  It would be really great to get the `en/dis` functionality into a release!

**Comment by jenlampton** [comment]
Yes!

**Comment by jenlampton** [comment]
no dice on core or custom modules.
```bash
> drush en ckeditor

	Error ckeditor does not exist in your Backdrop installation.
	Try downloading ckeditor first with the command: drush dl ckeditor

> drush en bblocks

	Error bblocks does not exist in your Backdrop installation.
	Try downloading bblocks first with the command: drush dl bblocks
```

**Comment by jenlampton** [comment]
and Drupal 7 still appears broken too?  I'm on the branch `serundeputy/ongoing-saga-of-en`. I wonder if I'm having some funny drush-cache issue, I did run `drush cc drush` but nothing seems to have changed. This sounds familiar and I'm starting to feel like the problem is me, and not Drush!

**Comment by serundeputy** [comment]
@jenlampton yes that is the correct branch.
I'm not sure what is going on here.  It does not seem to be using the latest code in that branch according to what you are reporting, which means `drush cc drush` was a good idea!

Scratching my head.  Something different about our environments set up or something I'm guessing.

**Comment by serundeputy** [comment]
@jenlampton Can you tell me your PHP version?

**Comment by jenlampton** [comment]
I most commonly switch between 5.3.29 and 5.5.26.

**Comment by serundeputy** [comment]
I wonder if some of the problem is with php < 5.5; drush 8 requires > 5.5.

**Comment by jenlampton** [comment]
My drush PHP is always 5.5.26.

**Comment by opi** [comment]
Testing serundeputy/ongoing-saga-of-en (PR#98). Works fine, can enable or disable core and contrib modules.
I found it strange that enabling a module ask for confirmation (y/n), but disabling does not.

```
$ drush status
 Backdrop version         :  1.8.x-dev                        
 Drush version            :  8.1.2                             
```

**Comment by serundeputy** [comment]
Thanks for testing @opi !

It would be great to be able to replicate this problem and have the list of `steps to reproduce` (STR); right now I have no angle to troubleshoot this.

I'm testing on local stack with Apache, MySQL, and php 5.5, 5.6, 7.0 and 7.1.

@jenlampton @opi what are your stacks?  does MAMP have something to do with it?

-----
> I found it strange that enabling a module ask for confirmation (y/n), but disabling does not.

I can add the conf `(y/n)` prompt to `drush dis`.

**Comment by opi** [comment]
My laptop runs a regular Debian Jessie, with PHP 5.6, Apache 2.4, MySQL 5.5 ; Drush commands are in `~/.drush/commands/backdrop`, currently checked out on `serundeputy/ongoing-saga-of-en` ; Drush caches are cleared before testing (`drush cc drush`).
I could run tests on other Linux flavors if you think it worth it, but I don't have any windows or macos system around me.

> I can add the conf (y/n) prompt to drush dis.

thanks ; If I found some free time I could provide a patch too.

Note that PHP5.5 has reached end-of-life: http://php.net/eol.php

**Comment by jenlampton** [comment]
> @jenlampton @opi what are your stacks?

I am running MAMP. However, my PHP version is specified in my `.bash_profile` using
 `export DRUSH_PHP=/Applications/MAMP/bin/php/php5.5.26/bin/php` to point to the version of PHP drush should be using, regardless of MAMP's settings.

**Comment by jenlampton** [comment]
I'm still unable to enable core or modules, but I do have the commits from May 7th in my `git log`. I also noticed that I'm unable to enable submodules, see https://github.com/backdrop-contrib/drush/issues/108

**Comment by jenlampton** [comment]
I'm still not able to enable core or custom modules. I get the following errors now:
```
Error ckeditor does not exist in your Backdrop installation.
    Try downloading ckeditor first with the command: drush dl ckeditor
```
that's not good advice :( 
---

* see https://github.com/backdrop-contrib/drush/issues/137 for core modules
* see https://github.com/backdrop-contrib/drush/issues/138 for custom modules

**Comment by quicksketch** [comment]
I posted a review to https://github.com/backdrop-contrib/drush/pull/98. Looks like this still needs a bit of work.

**Comment by serundeputy** [comment]
@quicksketch I followed some of the suggestions in your review thanks for that.

We still need a better way to handle detecting if a module is already in the file system:

```php
+  $file = file_exists(BACKDROP_ROOT . "/modules/contrib/$project") ||
+    file_exists(BACKDROP_ROOT . "/modules/$project") ||
+    file_exists(BACKDROP_ROOT . "/core/modules/$project") ||
+    file_exists(BACKDROP_ROOT . "/modules/custom/$project");
```

only checks the specific paths and as pointed out in the review there are other possibilities of a user having there own directory structure or multisites. `module_exists` will not work as that checks for installed and enabled.

**Comment by serundeputy** [comment]
@jenlampton @quicksketch I've updated the validation logic to use `system_rebuild_module_data()` if anyone is up for testing pull down the `ongoing-saga-of-en` branch and give it a whirl.

I've found that when switching branches issuing a `drush cc drush` in each terminal window (not just the one you make the code pull from)  is helpful/necessary.

**Comment by opi** [comment]
Maybe I miss something, but as for now, only module dependencies are enable, but not the desired modules. Here is my small patch : 
```diff --git a/commands/pm/backdrop_pm_enable.drush.inc b/commands/pm/backdrop_pm_enable.drush.inc
index 55c81bb..e5cd2d7 100644
--- a/commands/pm/backdrop_pm_enable.drush.inc
+++ b/commands/pm/backdrop_pm_enable.drush.inc
@@ -58,7 +58,7 @@ function backdrop_command_pm_enable() {
     }
   }
 
-  $operating_list = implode(', ', $dependents);
+  $operating_list = implode(', ', array_merge($projects, $dependents));
   $proceed = drush_confirm(
     "The following projects will be enabled: $operating_list.
     Do you want to enable the projects?"
@@ -74,6 +74,10 @@ function backdrop_command_pm_enable() {
       _enable_project($dependent, $module_list);
       $clear_cache = TRUE;
     }
+    foreach ($projects as $project) {
+      _enable_project($project, $module_list);
+      $clear_cache = TRUE;
+    }
   }
 
   if ($clear_cache) {
```

**Comment by serundeputy** [comment]
thanks for the review @opi my claim to fame is that that merge already happens on https://github.com/backdrop-contrib/drush/blob/ongoing-saga-of-en/commands/pm/backdrop_pm_enable.drush.inc#L56

I've tested and it is working for enabling modules and there dependencies for example:

```bash
geoff@yep backdrop $ drush en devel_generate
The following projects will be enabled: devel, devel_generate.
    Do you want to enable the projects? (y/n): y

	Success: module devel enabled.


	Success: module devel_generate enabled.
```
Enables both `devel` and `devel_generate`.

```bash
geoff@yep backdrop $ drush pml |grep devel
 	devel              	module  	enabled   	1.x-1.7.0
 	devel_generate     	module  	enabled   	1.x-1.7.0
 	devel_node_access  	module  	disabled  	1.x-1.7.0
```

And the inverse:

```bash
geoff@yep backdrop $ drush dis devel
The following projects will be disabled: devel_generate, devel.
    Do you want to disable the projects? (y/n): y

	Success: devel_generate, devel are disabled.
```

```bash
geoff@yep backdrop $ drush pml |grep devel
 	devel              	module  	disabled  	1.x-1.7.0
 	devel_generate     	module  	disabled  	1.x-1.7.0
 	devel_node_access  	module  	disabled  	1.x-1.7.0
```

did your testing not enable dependencies?

**Comment by serundeputy** [comment]
@opi I see what you are referring to now; In the tests listed above I was basically assuring that some dependencies would be found and when they were not things blew up.

I've added in to catch these cases.
PR updated: https://github.com/backdrop-contrib/drush/pull/98
Thanks!

**Comment by jenlampton** [comment]
Okay, I've noted all the problems we're having with `drush en` in other issues. Since https://github.com/backdrop-contrib/drush/pull/51 has been merged, I'm going to close this one.

**Comment by serundeputy** [comment]
@jenlampton that was merged into `master` but not the canonical branch `1.x-0.x` yet.

**Comment by jenlampton** [comment]
ugh, this project is a bit of a mess. can we delete the master branch? Also, can we rename 1.x-0.x 1.x-1.x, or make a new one? or, can you document how all these branches are being used if there's a method to it all?  I'm lost. (obviously)

**Comment by serundeputy** [comment]
@jenlampton I believe `master` branch is deleted; but you may have a local copy of `master` still?

**Comment by serundeputy** [comment]
the `1.x-0.x` reflects semver convention that this is not a stable project yet ... i.e. problems w/ compatibility between D7 and Backdrop.

**Comment by jenlampton** [comment]
Hm, I don't have a master... but I do have all these:
```
  remotes/contrib/1.x-0.0.x
  remotes/contrib/1.x-0.x
  remotes/contrib/105/local_modules
  remotes/contrib/46/drush_sqlsan
  remotes/contrib/allow-modules-to-def-drush-commands
  remotes/contrib/dev
  remotes/contrib/fix-cp-and-bcex
  remotes/contrib/ongoing-saga-of-en
  remotes/contrib/support-rsync
```

**Comment by serundeputy** [comment]
So `git checkout contrib/ongoing-saga-of-en` should have @opi 's commits on it

**Comment by jenlampton** [comment]
> the 1.x-0.x reflects semver convention that this is not a stable project yet ... i.e. problems w/ compatibility between D7 and Backdrop.

Hm, there's a big difference between `stable` and `problems w/ compatibility between D7 and Backdrop.`

**Comment by jenlampton** [comment]
> So git checkout contrib/ongoing-saga-of-en should have @opi 's commits on it

Yes, I'm not saying the commits were't committed at all. But as I said above, I believe they were pushed accidentally to that mystery branch on the main repo. 

The PR that was linked in the issue was from your [serendeputy/ongoing-saga-of-en](https://github.com/backdrop-contrib/drush/pull/98) branch, so that's the code everyone had been working off.

There is no PR (yet?) for this new branch where work is going on, so I've updated this issue now to note that it needs a PR, and removed the PR tags accordingly.

**Comment by opi** [comment]
I don't understand why PR #98 was closed...

**Comment by serundeputy** [comment]
@jenlampton @opi reopened PR 98 that has @opi and @serundeputy 's work on it.

**Comment by jenlampton** [comment]
More recent work was being added/committed to another branch - unrelated to that PR - that was not mentioned anywhere in this issue. Because of that, I wasted the time I had to work on this issue testing the PR that *was* linked from this issue, which of course wasn't going to be any help :/

> I don't understand why PR #98 was closed...

I closed that PR and updated this issue to save the next person who wanted to work on this issue (perhaps my future self) the same frustration of testing the linked PR, when it didn't contain any of the most recent changes. 

Usually, the latest changes are merged into the branch that the PR was generated from (in this case, that's `serundeputy:ongoing-saga-of-en` and then the branch is force-pushed to update the PR. In this case, the changes were not merged into that branch, so the linked PR was out-of-date.

**Comment by klonos** [comment]
@jenlampton in the PR you have commented to use `git checkout contrib/ongoing-saga-of-en`, but there is no such branch; while there exists a `ongoing-saga-of-en`:

```
$ cd ~/.drush/commands/backdrop/
$ git status
On branch 1.x-0.x
Your branch is up-to-date with 'origin/1.x-0.x'.
nothing to commit, working directory clean
$ git checkout contrib/ongoing-saga-of-en
error: pathspec 'contrib/ongoing-saga-of-en' did not match any file(s) known to git.
$ git checkout ongoing-saga-of-en
Branch ongoing-saga-of-en set up to track remote branch ongoing-saga-of-en from origin.
Switched to a new branch 'ongoing-saga-of-en'
$ drush cc drush
'drush' cache was cleared.                                                                                                                       [success]
```

Anyway, it seems that `pm-enable` works for modules, but not for themes:

```
$ cd /var/www/docroot
$ drush pm-enable theme_test
The following projects will be enabled: theme_test.
    Do you want to enable the projects? (y/n): y

	Success: module theme_test enabled.

$ drush pm-enable test_theme
The following projects will be enabled: test_theme.
    Do you want to enable the projects? (y/n): y

	Error test_theme does not exist in your Backdrop installation.
	Try downloading test_theme first with the command: drush dl test_theme
```

...nor does `backdrop-pm-enable` (for themes):

```
$ drush backdrop-pm-enable test_theme
The following projects will be enabled: test_theme.
    Do you want to enable the projects? (y/n): y

	Error test_theme does not exist in your Backdrop installation.
	Try downloading test_theme first with the command: drush dl test_theme
```

I hope I have gotten the correct branch.

**Comment by klonos** [comment]
...I thought that maybe that was because the theme I was trying to enable was in a non-standard theme folder (under `/core/modules/simpletest/tests/themes/test_theme`), but it does not work with the default core themes either:

```
$ drush pm-enable bartik    
The following projects will be enabled: bartik.
    Do you want to enable the projects? (y/n): y

	Error bartik does not exist in your Backdrop installation.
	Try downloading bartik first with the command: drush dl bartik

$ drush backdrop-pm-enable bartik
The following projects will be enabled: bartik.
    Do you want to enable the projects? (y/n): y

	Error bartik does not exist in your Backdrop installation.
	Try downloading bartik first with the command: drush dl bartik
```

**Comment by klonos** [comment]
...and it does not work for contrib themes either:

```
$ drush dl minicss

	Success:  Project minicss downloaded to /var/www/docroot/themes/minicss.

$ drush backdrop-pm-enable minicss
The following projects will be enabled: minicss.
    Do you want to enable the projects? (y/n): y

	Error minicss does not exist in your Backdrop installation.
	Try downloading minicss first with the command: drush dl minicss
```

**Comment by klonos** [comment]
...verbose output in case it helps:

```
$ drush backdrop-pm-enable minicss -v    
Undefined index: description command.inc:1296                             [notice]
Undefined index: description command.inc:1296                             [notice]
Undefined index: description command.inc:1296                             [notice]
Undefined index: description command.inc:1296                             [notice]
Undefined index: description command.inc:1296                             [notice]
Initialized Backdrop 1.12.x-dev root directory at /var/www/docroot        [notice]
Undefined index: description command.inc:1296                             [notice]
Undefined index: description command.inc:1296                             [notice]
Undefined index: description command.inc:1296                             [notice]
Undefined index: description command.inc:1296                             [notice]
Undefined index: description command.inc:1296                             [notice]
Initialized Backdrop site docroot at .                                    [notice]
Undefined index: description command.inc:1296                             [notice]
Undefined index: description command.inc:1296                             [notice]
Undefined index: description command.inc:1296                             [notice]
Undefined index: description command.inc:1296                             [notice]
Undefined index: description command.inc:1296                             [notice]
Undefined index: minicss backdrop_pm_enable.drush.inc:48                  [notice]
Trying to get property of non-object backdrop_pm_enable.drush.inc:48      [notice]
The following projects will be enabled: minicss.
    Do you want to enable the projects? (y/n): y

	Error minicss does not exist in your Backdrop installation.
	Try downloading minicss first with the command: drush dl minicss

Command dispatch complete
```

**Comment by serundeputy** [comment]
@klonos the current code is not making any  attempt at themes or layouts yet, just modules.  Once we stabilize that we should be able to apply the same pattern to themes and layouts.

**Comment by jackaponte** [comment]
Hi all! Getting `drush en <module>` is high priority for our team; we'd like to help move this along but I'm not sure where things are at. In [this earlier update on this issue](https://github.com/backdrop-contrib/drush/issues/7#issuecomment-441343694) @klonos says `pm-enable` is working for modules in a certain branch (maybe `ongoing-saga-of-en`) -- has that been confirmed? Is work needed on that branch to get it ready to be merged, or should one hoping to help work on this issue start elsewhere?

**Comment by serundeputy** [comment]
thanks @jackaponte ! the main blocker is that it `sometimes` under some unknown set of circumstances breaks drush for drupal 7.

I myself have not been able to nail down or reproduce the circumstances.

So, you can try out https://github.com/backdrop-contrib/drush/pull/98 and see if it:

- works for you on Backdrop and Drupal 7 sites
- does not work for you then detail
  - what the error is
  - as much about your system configuration as possible
  - php version
  - apache/nginx
   - Backdrop and Drupal versions tested

You can use [this branch](https://github.com/backdrop-contrib/drush/pull/98)  and mitigate by either using a site local backdrop drush; or installing in a scoped system like docker or Lando.

**Comment by jackaponte** [comment]
Testing the `serundeputy:ongoing-saga-of-en` branch, `drush en` and `drush dis` with the `stage_file_proxy`, `devel`, `devel_generate` (to test dependencies) and `contact` modules on my local machine (Debian 9, Apache 2.4.25, PHP 7.2, Drush 8.2.3) on the following six different sites and it works with no errors:

* Backdrop 1.12.6
* Backdrop 1.12.3
* Backdrop 1.13.1
* Drupal 7.67
* Drupal 7.67
* Drupal 7.67

After all that success I tested on six more sites on a different server: Debian 9, Apache 2.4.25, PHP 7.0, Drush 8.1.18:

* Backdrop 1.12.6
* Backdrop 1.12.6
* Backdrop 1.12.6
* Drupal 7.67
* Drupal 7.67
* Drupal 7.67

When I say it works, I mean the modules are properly enabled and disabled; output is still different from Drupal 7 output and could probably use some work!

But for the purposes of just getting `drush en` and `drush dis` working for core and contrib modules, this is working on the 12 different D7 and Backdrop instances that I tested.

Let me know if I can provide more info or do more testing!

**Comment by serundeputy** [comment]
That is great news @jackaponte do you have any mac users that could test on a local?

**Comment by jenlampton** [comment]
My local is still running on MAMP, let me give it a test...
* fetched `serundeputy` remote
* checked out latest `serundeputy/ongoing-saga-of-en` branch

---

**Tested a Backdrop site (on MAMP):**
1a) Contrib module enable test `drush en devel -y`
```
    Do you want to enable devel? (y/n): y
	Success module devel enabled.
```
1b) Contrib module disable test `drush dis devel -y`
```
    The following projects will be disabled: devel.
    Do you want to disable the projects? (y/n): y
	Success: devel are disabled.
```

1c) Contrib submodule enable w/ dependancies test `drush en devel_generate -y`
```
	Error devel_generate does not exist in your Backdrop installation.
	Try downloading devel_generate first with the command: drush dl devel_generate
```
2) Core module `drush en dashboard -y` (see https://github.com/backdrop-contrib/drush/issues/137)
```
    Error dashboard does not exist in your Backdrop installation. 
	Try downloading dashboard first with the command: drush dl dashboard
```
3) Custom module `drush en custom_blocks -y` (see https://github.com/backdrop-contrib/drush/issues/138) 
```
	Error boots_blocks does not exist in your Backdrop installation.
	Try downloading custom_blocks first with the command: drush dl custom_blocks
```

---

**Tested a Drupal 7 site (on MAMP):**
1a) Contrib module `drush en protected_pages -y`
```
    The following extensions will be enabled: protected_pages
    Do you really want to continue? (y/n): y
    protected_pages was enabled successfully.
```
1b) Contrib module `drush dis devel -y`
```
    The following extensions will be disabled: devel
	Do you really want to continue? (y/n): y
    devel was disabled successfully.
```
1c) Contrib submodule enable w/ dependancies test `drush en devel_generate -y` (**did not enable the required module**)
```
	The following extensions will be enabled: devel_generate
    Do you really want to continue? (y/n): y
    devel_generate was enabled successfully. 
```
2) Core module `drush en dashboard -y`
```
    The following extensions will be enabled: dashboard
    Do you really want to continue? (y/n): y
    dashboard was enabled successfully.   
```
3) Custom module `drush en custom_fields -y`
```
    The following extensions will be enabled: custom_fields
    Do you really want to continue? (y/n): y
    custom_fields was enabled successfully. 
```

**Comment by jenlampton** [comment]
@serundeputy this seems to work fine now on my local D7 sites. :)

I say we merge this so we can and start working on https://github.com/backdrop-contrib/drush/issues/136 and https://github.com/backdrop-contrib/drush/issues/137

**Comment by jenlampton** [comment]
@jackaponte I'm getting different results. Can you please post the exact drush commands you were running so I can compare? In particular, what you did for core modules, and for the one with dependancies.

**Comment by jackaponte** [comment]
> @jackaponte I'm getting different results. Can you please post the exact drush commands you were running so I can compare? In particular, what you did for core modules, and for the one with dependancies.

Here you go: my local tests with responses corresponding to your numbering in your post above; all testing today is with the most recent commit `99d7f2c869` in the `serundeputy/ongoing-saga-of-en` branch.

**Tested a Backdrop 1.13.1 site:**

1a) Contrib module enable test `drush en devel -y`

```
The following projects will be enabled: devel.
    Do you want to enable the projects? (y/n): y

	Success: module devel enabled.
```

1b) Contrib module disable test `drush dis devel -y`

```
The following projects will be disabled: devel.
    Do you want to disable the projects? (y/n): y

	Success: devel are disabled.
```

1c) Contrib submodule enable w/ dependancies test `drush en devel_generate -y`

```
The following projects will be enabled: devel, devel_generate.
    Do you want to enable the projects? (y/n): y

	Success: module devel enabled.


	Success: module devel_generate enabled.
```

2) Core module `drush en dashboard -y`

```
The following projects will be enabled: dashboard.
    Do you want to enable the projects? (y/n): y

	Success: module dashboard enabled.
```

3) (No custom modules to test here)

----

**Tested a Drupal 7.67 site:**

1a) Contrib module `drush en devel -y`

```
The following extensions will be enabled: devel
Do you really want to continue? (y/n): y
devel was enabled successfully.                                                                                                                                                    [ok]
devel defines the following permissions: access devel information, execute php code, switch users
```

1b) Contrib module `drush dis devel -y`

```
The following extensions will be disabled: devel
Do you really want to continue? (y/n): y
devel was disabled successfully.                                                                                                                                                   [ok]
```

1c) Contrib submodule enable w/ dependancies test `drush en devel_generate -y`

This one is tricky: Devel submodules in both Drupal and Backdrop aren't all properly given `devel` as a dependency, including `devel_generate` for D7! (It's set as a dependency in Backdrop.) So I had to add `dependencies[] = devel` to `devel_generate.info` in order to test the command with the same submodule in Backdrop and Drupal. After making that change:

```
The following extensions will be enabled: devel_generate, devel
Do you really want to continue? (y/n): y
devel_generate was enabled successfully.                                                                                                                                           [ok]
devel was enabled successfully.                                                                                                                                                    [ok]
devel defines the following permissions: access devel information, execute php code, switch users
```

2) Core module `drush en dashboard -y`

```
The following extensions will be enabled: dashboard
Do you really want to continue? (y/n): y
dashboard was enabled successfully.                                                                                                                                                [ok]
dashboard defines the following permissions: access dashboard
```

3) Custom module `drush en ilrf_actions -y`

```
The following extensions will be enabled: ilrf_actions
Do you really want to continue? (y/n): y
ilrf_actions was enabled successfully.                                                                                                                                             [ok]
```

**Comment by jenlampton** [comment]
Sanity checks:
* confirmed I am also running the 8.2.3 tag for drush 8
* Confirmed that the last commit I have on `serundeputy/ongoing-saga-of-en` is also `99d7f2c869db0577`
* ran `drush cc drush`
* closed and re-opened terminal window to get a new session or whatever

Things in my bashrc file:
* drush PHP version `DRUSH_PHP=/Applications/MAMP/bin/php/php7.1.6/bin/php`
* drush alias `alias drush=/Users/jlampton/drush-8/drush`

Locations of things:
* drush 8 is locaed at `/Users/jlampton/drush-8`
* backdrop-drush is locaed at `/Users/jlampton/drush-8/commands/backdrop`
* backdrop commands located at `/Users/jlampton/drush-8/commands/backdrop/commands`
* .drush is located at `/Users/jlampton/.drush`
* local commands located at `/Users/jlampton/.drush/commands`

Also tried this:
* backdrop-drush loction: `/Users/jlampton/.drush/commands/backdrop`
* backdrop commands located at `/Users/jlampton/.drush/commands/backdrop/commands`

**Tested a Backdrop 1.13.1 site on MAMP:**

1a) matches your result
1b) matches your result
1c) **still fails** Contrib submodule enable w/ dependancies test `drush en devel_generate -y`
```
	Error devel_generate does not exist in your Backdrop installation.
	Try downloading devel_generate first with the command: drush dl devel_generate
```
2) **still fails** Core module `drush en dashboard -y'
```
	Error dashboard does not exist in your Backdrop installation.
	Try downloading dashboard first with the command: drush dl dashboard
```
3) **still fails** Custom module `drush en custom_blocks -y`
```
	Error custom_blocks does not exist in your Backdrop installation.
	Try downloading custom_blocks first with the command: drush dl custom_blocks
```

**Tested a Drupal 7.67 site on MAMP:**

1a) matches your result
1b) matches your result 
1c) matches your result (also added dependencies[] = devel to devel_generate.info first)
2) matches your result
3) matches your result

**Comment by jenlampton** [comment]
This is weird:

Deleting the `commands` directory entirely from the backdrop drush project does not change the above results at all. I believe that's where all the Backdrop specific command code is. The code that makes things like `drush en` work for Backdrop sites.... But on my computer it's not even running.

**Comment by jackaponte** [comment]
Are you using a different copy of `drush` installed elsewhere on your computer by accident? I've done that before...many, many times...

**Comment by jenlampton** [comment]
How would it know I was running a Backdrop site if I were?

**Comment by jackaponte** [comment]
> How would it know I was running a Backdrop site if I were?

That other copy also has a different version of Backdrop commands installed? Just a guess!

**Comment by jenlampton** [comment]
@jackaponte yep, that was it! 
`which drush` says `/Users/jlampton/.composer/vendor/bin/drush`
I really hate composer. It's such a piece of garbage.... :( 
ahhhhh the joy of `rm -rf ~/.composer`

Okay, fixed that, testing again...

**Comment by jenlampton** [comment]
**Tested a Backdrop 1.13.1 site on MAMP:**

1c) **success** Contrib submodule enable w/ dependancies test `drush en devel_generate -y`
```
The following projects will be enabled: devel, devel_generate.
    Do you want to enable the projects? (y/n): y
	Success: module devel enabled.
	Success: module devel_generate enabled.
```
2) **success** Core module `drush en dashboard -y'
```
The following projects will be enabled: dashboard.
    Do you want to enable the projects? (y/n): y
	Success: module dashboard enabled.
```

3) **success** Custom module `drush en custom_blocks -y`
```
The following projects will be enabled: custom_blocks.
    Do you want to enable the projects? (y/n): y
	Success: module custom_blocks enabled.
```
---
**Tested a Drupal 7.67 site on MAMP:**

1a) Contrib module `drush en devel -y`
```
The following extensions will be enabled: devel
Do you really want to continue? (y/n): y
devel was enabled successfully.                                                                                                                                                    
devel defines the following permissions: access devel information, execute php code, switch users
```
1b) Contrib module `drush dis devel -y`
```
The following extensions will be disabled: devel, devel_generate
Do you really want to continue? (y/n): y
devel_generate was disabled successfully.                                                                       [ok]
devel was disabled successfully.
```
1c) Contrib submodule enable w/ dependancies test `drush en devel_generate -y`
```
The following extensions will be enabled: devel_generate, devel
Do you really want to continue? (y/n): y
devel_generate was enabled successfully.
devel was enabled successfully.
devel defines the following permissions: access devel information, execute php code, switch users
```
2) Core module `drush en dashboard -y`
```
The following extensions will be enabled: dashboard
Do you really want to continue? (y/n): y
dashboard was enabled successfully.
dashboard defines the following permissions: access dashboard
```
3) Custom module `drush en custom_fields -y`
```
The following extensions will be enabled: custom_fields
Do you really want to continue? (y/n): y
custom_fields was enabled successfully. 
```

**Comment by jenlampton** [comment]
@serundeputy 	I think this is close enough to merge. It's usable and doesn't break anything, and everyone will benefit from it being in Drush :) All the remaining issues are spacing or singular/plural problems and are only cosmetic.

RTBC :)

**Comment by serundeputy** [comment]
Thanks @opi @jenlampton @jackaponte @klonos @wesruv for your code, comments, testing and efforts to move this issue forward.

It has been an epic battle starting back in 2016, but I'm pleased to say this is merged and will ship with `0.2.0`.

**Comment by jackaponte** [comment]
w00t, thanks all for the time and effort put into this!
